@extends('layout.template')

@section('content')
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>NIM</th>
                <th>Kelas</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Agus</td>
                <td>12212</td>
                <td>A</td>
            </tr>
        </tbody>
        <tbody>
            <tr>
                <td>2</td>
                <td>Haikal</td>
                <td>12132</td>
                <td>A</td>
            </tr>
        </tbody>
        <tbody>
            <tr>
                <td>3</td>
                <td>Bagus</td>
                <td>12321</td>
                <td>A</td>
            </tr>
        </tbody>
        <tbody>
            <tr>
                <td>4</td>
                <td>Adul</td>
                <td>124313</td>
                <td>B</td>
            </tr>
        </tbody>
        <tbody>
            <tr>
                <td>5</td>
                <td>Ica</td>
                <td>123312</td>
                <td>B</td>
            </tr>
        </tbody>
    </table>
@endsection
